#
# GENERAL SETTINGS
#
format = "$sudo$directory$git_branch$git_status$git_state$character"

[sudo]
disabled = false
symbol = "root "
style = 'dimmed'

#
# TRANSIENT PROMPT
#
# [transient_prompt]
# enabled = true
# format = "❯"
# prompt_style = "dimmed"

#
# PROMPT STYLE
#
[character]
success_symbol = "[❯](green bold)"
error_symbol = "[❯](red bold)"
vicmd_symbol = "[❮](yellow bold)"

#
# DIRECTORY
#
[directory]
truncate_to_repo = true
truncation_length = 2

#
# GIT
#
[git_branch]
format = "[$branch]($style) "
style = "dimmed"

[git_status]
format = "[$all_status$ahead_behind]($style) "
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
